"use client";
import {useEffect,useState} from "react";
type Tile={id:number;symbol:string;matched:boolean};
const symbols=["日","月","花","竹","鳥","魚","山","波","春","秋","雪","風"];
const makeTiles=()=>[...symbols,...symbols].sort(()=>Math.random()-.5).map((symbol,id)=>({id,symbol,matched:false}));
export default function MahjongMemoryPage(){const[tiles,setTiles]=useState<Tile[]>(makeTiles),[picked,setPicked]=useState<number[]>([]),[moves,setMoves]=useState(0),[time,setTime]=useState(0),[running,setRunning]=useState(false),[won,setWon]=useState(false);
useEffect(()=>{if(!running)return;const t=window.setInterval(()=>setTime(v=>v+1),1000);return()=>window.clearInterval(t)},[running]);
useEffect(()=>{if(picked.length!==2)return;const[a,b]=picked,ta=tiles.find(t=>t.id===a),tb=tiles.find(t=>t.id===b);if(ta?.symbol===tb?.symbol){setTiles(v=>v.map(t=>t.id===a||t.id===b?{...t,matched:true}:t));setPicked([])}else{const t=window.setTimeout(()=>setPicked([]),650);return()=>window.clearTimeout(t)}},[picked,tiles]);
useEffect(()=>{if(tiles.length&&tiles.every(t=>t.matched)){setWon(true);setRunning(false)}},[tiles]);
const start=()=>{setTiles(makeTiles());setPicked([]);setMoves(0);setTime(0);setWon(false);setRunning(true)};
const choose=(id:number)=>{if(!running||picked.length===2||picked.includes(id)||tiles.find(t=>t.id===id)?.matched)return;setPicked(v=>[...v,id]);setMoves(v=>v+1)};
return <main style={{minHeight:"100vh",padding:"48px 20px",background:"#071018",color:"#eff",fontFamily:"system-ui"}}><section style={{maxWidth:850,margin:"auto"}}><p style={{letterSpacing:".16em",opacity:.6}}>JAPANESE LEARNING DOJO · GAME</p><h1 style={{fontSize:"clamp(2rem,6vw,4rem)",margin:"8px 0"}}>Mahjong Memory</h1><p>Match the Japanese tiles and remember the characters.</p><div style={{display:"flex",gap:24,fontFamily:"monospace",margin:"22px 0"}}><span>MOVES {moves}</span><span>TIME {time}s</span></div><button onClick={start} style={{padding:"12px 20px",borderRadius:10,border:"1px solid #4cc",background:"#10252b",color:"#eff",cursor:"pointer"}}>{running?"Restart":"Start game"}</button><div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:10,marginTop:28}}>{tiles.map(t=>{const open=picked.includes(t.id)||t.matched;return <button key={t.id} onClick={()=>choose(t.id)} aria-label={open?t.symbol:"Hidden tile"} style={{aspectRatio:"3/4",borderRadius:10,border:"1px solid #345",background:t.matched?"#123f3d":open?"#f2eee4":"#101b23",color:open?"#17232a":"#9bd",fontSize:"clamp(22px,4vw,38px)",cursor:running?"pointer":"default",boxShadow:t.matched?"0 0 18px #3cc":"none"}}>{open?t.symbol:"花"}</button>})}</div>{won&&<h2 style={{marginTop:28}}>Completed — {moves} moves in {time}s.</h2>}</section></main>}